### ISSUE TITLE
Fails with create-react-app (and others)

### ISSUE THREAD

**Issue by d-asensio** [mrmartineau/design-system-utils#22]
Hi @mrmartineau ,

First of all let me thank you for this project, it is really helping us to build our design system. I think that the idea behind it is radically simple, but radically powerful as well.

That being said, I would like to report an issue I have been having while using this project along with [create-react-app](https://github.com/facebookincubator/create-react-app), [nwb](https://github.com/insin/nwb) and [Next.js](https://github.com/zeit/next.js/).

Let's focus in create-react-app, since the problem is the same with all the aforementioned tools.

## Steps to reproduce the issue (hope it helps)
https://asciinema.org/a/4GmMG7GzlGuTbd43COKQxHliO

I used the example code, but the code itself is not relevant.

As you can see in the asciinema, it can be fixed by changing the following lines in the packages.json:

https://github.com/mrmartineau/design-system-utils/blob/74f9e344cddf8257a229602115d21834036e3570/package.json#L5-L6

## Why is it failing?

The problem is that create-react-app don't compile the modules source with babel, triggering the start script I don't get the error because the js is not minified, but generating the production build the js is minified and the minification fails because the source that webpack imports is `./src/index.js` which is written in ES2015 and has tokens the minifier don't recognize.

Looking at the webpack docs: [resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolve-mainfields)

It looks like the`module` field is in the second priority order (preceded by `browser` and followed by `main`) so is the one used to resolve the package.

## My proposal: Add a `browser` field to the package.json

Theoretically it would fix the issue, but I would like to know your opinion before submitting a PR.

**Comment by d-asensio** [comment]
If you want to test it, I merged in my fork's master https://github.com/d-asensio/design-system-utils.git

**Comment by mrmartineau** [comment]
@d-asensio thank you for submitting the issue and the PR, I will merge it now. I wasn't aware of the priority order.

Love the detail you gave!
