### ISSUE TITLE
Feature Request: 'toPx' function

### ISSUE THREAD

**Issue by oyeanuj** [mrmartineau/design-system-utils#4]
Hi again @mrmartineau! I've been finding in a couple of cases where I'd like to get the `px` value of my font from the modular scale - something like the reverse of `pxTo` function which given a value in `em` calculates the px value using the `baseFontSize`?

Is that something you can see being useful to others as well?

**Comment by mrmartineau** [comment]
Hi @oyeanuj, do you mean an `em`/`rem` to `px` converter? If so it is easy to add, but how would it be consumed? As part of the `fontSize` function or by itself?

**Comment by oyeanuj** [comment]
@mrmartineau I was thinking along the same lines of the `pxTo` function. Personally, I ended up needing it when I was trying to get one of the sizes, but in `px` (rather than the default `em` unit that I had set up).

Another option could to be offer an optional argument to the `fontSize` method where one can specify the unit and the function would return the value in that unit?

**Comment by mrmartineau** [comment]
hi @oyeanuj, this has been done now, take a look at https://github.com/mrmartineau/design-system-utils/releases/tag/v0.6.0 and let me know what you think.
