### ISSUE TITLE
Difference with styled-system?

### ISSUE THREAD

**Issue by muhajirframe** [mrmartineau/design-system-utils#50]
I'd love to know the difference of design-system-utils with https://github.com/jxnblk/styled-system .
Is it similiar or have different goals?

**Comment by mrmartineau** [comment]
@muhajirframe I'm glad you asked. They are similar, they serve the same goal, in fact I took a lot of inspiration from styled-system when making design-system-utils, but they are different in how that goal is achieved. For one, styled-system only works with styled-components, and design-system-utils is agnostic of any CSS-in-JS library.

Both libs ensure a consistent design-system, and styled-system's solution is elegant, but design-system-utils allows you to have ultimate control of your styles. Fun fact: they can, in fact, be used together.

I'm not sure if that answer's your question, so let me know if you want me to elaborate on anything.

**Comment by mrmartineau** [comment]
@muhajirframe let me know if you have any other questions, but for now, I'll close this issue.
